"""OpenAI-powered SOC 2 compliance report generator."""

import json
import os
from datetime import datetime, timedelta
from typing import Any


class OpenAIReporter:
    """Generates SOC 2 compliance reports using OpenAI or demo mode."""

    def __init__(self) -> None:
        """Initialize the reporter, checking for demo mode."""
        self.demo_mode = os.getenv("DEMO_MODE", "false").lower() in ("true", "1", "yes")
        self.timestamp = datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
        self.report_date = datetime.utcnow().strftime("%Y-%m-%d")

        if self.demo_mode:
            print("[DEMO] OpenAI Reporter initialized in DEMO MODE")
            print("[DEMO] Skipping OpenAI API credential validation")
            self.client = None
        else:
            api_key = os.getenv("OPENAI_API_KEY")
            if not api_key:
                raise ValueError(
                    "OPENAI_API_KEY environment variable is required. "
                    "Set DEMO_MODE=true to run without credentials."
                )
            try:
                from openai import OpenAI
                self.client = OpenAI(api_key=api_key)
            except ImportError:
                raise ImportError(
                    "openai package is required. Install with: pip install openai"
                )

    def generate_report(self, evidence: dict[str, Any] | None = None) -> str:
        """Generate a SOC 2 compliance report.

        Args:
            evidence: Collected evidence data. If None, uses demo data in demo mode.

        Returns:
            The generated report as a string.
        """
        if self.demo_mode:
            return self._generate_demo_report()

        if not evidence:
            raise ValueError("Evidence data is required in production mode.")

        return self._generate_openai_report(evidence)

    def _generate_openai_report(self, evidence: dict[str, Any]) -> str:
        """Generate report using OpenAI API.

        Args:
            evidence: Collected evidence data.

        Returns:
            The generated report from OpenAI.
        """
        prompt = self._build_prompt(evidence)
        response = self.client.chat.completions.create(
            model="gpt-4",
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a SOC 2 compliance expert. Generate a detailed "
                        "compliance report based on the provided evidence."
                    ),
                },
                {"role": "user", "content": prompt},
            ],
            temperature=0.3,
            max_tokens=4000,
        )
        return response.choices[0].message.content

    def _build_prompt(self, evidence: dict[str, Any]) -> str:
        """Build the prompt for OpenAI from evidence data.

        Args:
            evidence: Collected evidence data.

        Returns:
            Formatted prompt string.
        """
        return (
            f"Generate a SOC 2 Type II compliance report based on the following "
            f"evidence collected on {self.report_date}:\n\n"
            f"{json.dumps(evidence, indent=2, default=str)}"
        )

    def _generate_demo_report(self) -> str:
        """Generate a realistic demo compliance report without calling OpenAI.

        Returns:
            A comprehensive SOC 2 compliance report string.
        """
        audit_period_start = (datetime.utcnow() - timedelta(days=180)).strftime("%B %d, %Y")
        audit_period_end = datetime.utcnow().strftime("%B %d, %Y")
        org_name = "Acme Cloud Services, Inc."

        report = f"""
{'='*80}
                    SOC 2 TYPE II COMPLIANCE ASSESSMENT REPORT
{'='*80}

Organization:     {org_name}
Report Date:      {self.report_date}
Audit Period:     {audit_period_start} - {audit_period_end}
Generated By:     Evidence Tracer Agent (Demo Mode)
Classification:   CONFIDENTIAL

{'='*80}


1. EXECUTIVE SUMMARY
{'─'*80}

This report presents the findings of an automated SOC 2 Type II compliance
assessment conducted for {org_name} covering the period from
{audit_period_start} to {audit_period_end}.

The assessment evaluated the organization's AWS infrastructure against the
AICPA Trust Service Criteria (TSC) across five categories: Security,
Availability, Processing Integrity, Confidentiality, and Privacy.

OVERALL COMPLIANCE SCORE: 78/100 (Satisfactory with Improvements Needed)

Key Findings:
  - 5 of 8 controls assessed are COMPLIANT
  - 2 controls require REMEDIATION within 30 days
  - 1 control has a CRITICAL gap requiring immediate attention
  - Infrastructure demonstrates strong foundational security posture
  - Monitoring and logging capabilities exceed baseline requirements

Positive Observations:
  - CloudTrail logging is enabled across all regions
  - Multi-factor authentication is enforced for console access
  - Encryption at rest is configured for all S3 buckets and RDS instances
  - VPC flow logs capture network traffic for forensic analysis


2. EVIDENCE OVERVIEW
{'─'*80}

Evidence was collected from the following AWS services:

  Service                  | Items Collected | Status
  ─────────────────────────┼─────────────────┼──────────────
  AWS CloudTrail           |      2,847      | Complete
  AWS Config               |        156      | Complete
  AWS IAM                  |         43      | Complete
  Amazon GuardDuty         |         12      | Complete
  AWS Security Hub         |         89      | Complete
  Amazon S3                |         34      | Complete
  Amazon RDS               |          8      | Complete
  AWS KMS                  |         15      | Complete
  ─────────────────────────┼─────────────────┼──────────────
  TOTAL                    |      3,204      |

Collection Period: {audit_period_start} - {audit_period_end}
Collection Method: Automated API interrogation via Evidence Tracer Agent
Data Integrity: SHA-256 checksums computed for all evidence artifacts


3. CONTROL ASSESSMENT
{'─'*80}

3.1 CC6.1 - Logical and Physical Access Controls
    Status: COMPLIANT
    Score:  92/100

    Evidence:
    - IAM policies follow least-privilege principle (43 policies reviewed)
    - No wildcard (*) permissions found in production IAM policies
    - MFA enforcement verified for all 12 IAM users with console access
    - Service accounts use role-based temporary credentials via STS
    - Password policy enforces: 14+ characters, rotation every 90 days

    Finding: Access controls are well-implemented and consistently enforced.

{'─'*40}

3.2 CC6.2 - System Access Registration and Authorization
    Status: COMPLIANT
    Score:  88/100

    Evidence:
    - User provisioning follows documented onboarding workflow
    - Access reviews conducted quarterly (last review: 15 days ago)
    - 3 dormant accounts identified and flagged for review
    - SSO integration active via AWS IAM Identity Center

    Finding: Registration processes are mature. Minor improvement needed
    for dormant account cleanup automation.

{'─'*40}

3.3 CC6.3 - Network Security Controls
    Status: COMPLIANT
    Score:  85/100

    Evidence:
    - VPC flow logs enabled across all 4 VPCs
    - Security groups follow deny-by-default principle
    - No security groups with 0.0.0.0/0 ingress on sensitive ports
    - AWS WAF deployed on all public-facing ALBs
    - Network ACLs provide additional layer of subnet-level filtering

    Finding: Network segmentation and filtering are properly configured.

{'─'*40}

3.4 CC6.6 - Encryption and Key Management
    Status: COMPLIANT
    Score:  90/100

    Evidence:
    - All S3 buckets use AES-256 or AWS KMS encryption
    - RDS instances encrypted with customer-managed KMS keys
    - KMS key rotation enabled (annual rotation policy)
    - TLS 1.2+ enforced for all data in transit
    - 15 KMS keys reviewed, all with appropriate key policies

    Finding: Encryption posture is strong across all data stores.

{'─'*40}

3.5 CC7.1 - System Monitoring and Anomaly Detection
    Status: COMPLIANT
    Score:  87/100

    Evidence:
    - CloudTrail enabled in all 16 AWS regions
    - GuardDuty active with 12 findings in audit period (all resolved)
    - CloudWatch alarms configured for critical metrics (47 alarms)
    - Security Hub aggregating findings from 5 integrated services
    - Average detection-to-response time: 4.2 hours

    Finding: Monitoring capabilities are comprehensive and well-maintained.

{'─'*40}

3.6 CC7.2 - Incident Response Procedures
    Status: NEEDS REMEDIATION (30 days)
    Score:  62/100

    Evidence:
    - Incident response plan documented but last updated 8 months ago
    - No evidence of tabletop exercises in the audit period
    - Escalation matrix references 2 former employees
    - CloudWatch alerts route to a shared email, not a ticketing system
    - Mean time to acknowledge: 6.8 hours (target: < 1 hour)

    Finding: Incident response documentation and processes require updates.
    Escalation contacts are outdated, and response times exceed targets.

    Recommendation:
    a) Update incident response plan within 30 days
    b) Conduct quarterly tabletop exercises
    c) Integrate alerts with PagerDuty or Opsgenie for faster response
    d) Update escalation matrix with current team members

{'─'*40}

3.7 CC8.1 - Change Management Controls
    Status: NEEDS REMEDIATION (30 days)
    Score:  65/100

    Evidence:
    - Infrastructure changes deployed via Terraform (IaC)
    - 23% of changes in audit period bypassed the CI/CD pipeline
    - No mandatory code review policy enforced in GitHub
    - Staging environment parity is at 78% (target: >95%)
    - Rollback procedures documented but not tested

    Finding: While IaC adoption is positive, enforcement gaps exist.
    Direct console changes and skipped reviews introduce risk.

    Recommendation:
    a) Enforce branch protection rules requiring PR reviews
    b) Implement AWS Service Control Policies to prevent console changes
    c) Achieve staging-production parity above 95%
    d) Schedule quarterly rollback drills

{'─'*40}

3.8 CC9.1 - Risk Assessment and Mitigation
    Status: CRITICAL - Immediate Action Required
    Score:  45/100

    Evidence:
    - Formal risk register not found or not maintained
    - No documented risk assessment performed in the audit period
    - Third-party vendor risk assessments incomplete (2 of 7 vendors)
    - Business continuity plan references deprecated infrastructure
    - Disaster recovery RTO/RPO targets not validated with testing

    Finding: Risk management program has significant gaps that must be
    addressed to achieve SOC 2 compliance.

    Recommendation:
    a) Establish and maintain a formal risk register immediately
    b) Conduct a comprehensive risk assessment within 14 days
    c) Complete vendor risk assessments for all critical third parties
    d) Update BCP to reflect current infrastructure
    e) Conduct DR testing to validate RTO/RPO targets


4. FINDINGS & RECOMMENDATIONS SUMMARY
{'─'*80}

  Priority   | Control | Finding                              | Due Date
  ───────────┼─────────┼──────────────────────────────────────┼─────────────
  CRITICAL   | CC9.1   | Risk management program gaps         | Immediate
  HIGH       | CC7.2   | Incident response plan outdated      | 30 days
  HIGH       | CC8.1   | Change management enforcement gaps   | 30 days
  MEDIUM     | CC6.2   | Dormant account cleanup needed       | 60 days
  LOW        | CC7.1   | Response time optimization           | 90 days
  ───────────┼─────────┼──────────────────────────────────────┼─────────────

Total Findings: 5
  - Critical: 1
  - High:     2
  - Medium:   1
  - Low:      1


5. RISK ASSESSMENT TABLE
{'─'*80}

  Risk Area                | Likelihood | Impact   | Risk Level | Trend
  ─────────────────────────┼────────────┼──────────┼────────────┼──────────
  Unauthorized Access      | Low        | High     | MEDIUM     | Stable
  Data Breach              | Low        | Critical | HIGH       | Improving
  Service Disruption       | Medium     | High     | HIGH       | Stable
  Compliance Violation     | Medium     | High     | HIGH       | Improving
  Insider Threat           | Low        | Medium   | MEDIUM     | Stable
  Third-Party Risk         | Medium     | Medium   | MEDIUM     | Declining
  Configuration Drift      | High       | Medium   | HIGH       | Improving
  Insufficient Monitoring  | Low        | High     | MEDIUM     | Improving
  ─────────────────────────┼────────────┼──────────┼────────────┼──────────

  Overall Risk Posture: MODERATE
  Trend: IMPROVING (based on 180-day analysis)


6. NEXT STEPS
{'─'*80}

  Immediate (0-14 days):
  [ ] Establish formal risk register with identified risks and owners
  [ ] Conduct organization-wide risk assessment
  [ ] Update incident response escalation contacts

  Short-term (15-30 days):
  [ ] Update incident response plan and conduct tabletop exercise
  [ ] Enforce branch protection and mandatory code reviews
  [ ] Implement SCP guardrails for production environment changes
  [ ] Complete outstanding vendor risk assessments

  Medium-term (30-90 days):
  [ ] Achieve staging-production environment parity (>95%)
  [ ] Implement automated dormant account detection and remediation
  [ ] Integrate alerting with dedicated incident management platform
  [ ] Conduct disaster recovery validation test
  [ ] Schedule recurring quarterly compliance reviews

  Long-term (90+ days):
  [ ] Pursue SOC 2 Type II formal audit with external auditor
  [ ] Implement continuous compliance monitoring dashboard
  [ ] Establish compliance-as-code pipeline integration
  [ ] Develop automated evidence collection for all TSC controls


{'='*80}
                              END OF REPORT
{'='*80}

Report ID:       RPT-DEMO-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}
Generated:       {self.timestamp}
Classification:  CONFIDENTIAL - For authorized recipients only
Agent Version:   Evidence Tracer Agent v1.0.0 (Demo)

Note: This report was generated in DEMO MODE using simulated evidence
data. In production, evidence is collected directly from your AWS
environment and analyzed using OpenAI GPT-4 for intelligent assessment.
{'='*80}
"""
        return report

    def save_report(self, report: str, output_dir: str = "data") -> str:
        """Save the generated report to a file.

        Args:
            report: The report content to save.
            output_dir: Directory to save the report in.

        Returns:
            The path to the saved report file.
        """
        os.makedirs(output_dir, exist_ok=True)
        filename = f"soc2_compliance_report_{self.report_date}.txt"
        filepath = os.path.join(output_dir, filename)

        with open(filepath, "w") as f:
            f.write(report)

        print(f"Report saved to: {filepath}")
        return filepath

    def save_report_json(self, output_dir: str = "data") -> str:
        """Save a JSON summary of the report metadata.

        Args:
            output_dir: Directory to save the JSON in.

        Returns:
            The path to the saved JSON file.
        """
        os.makedirs(output_dir, exist_ok=True)
        filename = f"soc2_report_metadata_{self.report_date}.json"
        filepath = os.path.join(output_dir, filename)

        metadata = {
            "report_date": self.report_date,
            "generated_at": self.timestamp,
            "demo_mode": self.demo_mode,
            "overall_score": 78 if self.demo_mode else None,
            "controls_assessed": 8,
            "controls_compliant": 5,
            "controls_needs_remediation": 2,
            "controls_critical": 1,
            "findings": {
                "critical": 1,
                "high": 2,
                "medium": 1,
                "low": 1,
                "total": 5,
            },
            "risk_posture": "MODERATE",
            "risk_trend": "IMPROVING",
        }

        with open(filepath, "w") as f:
            json.dump(metadata, f, indent=2)

        print(f"Report metadata saved to: {filepath}")
        return filepath
