"""
Report Generator
Produces evidence trace reports in Markdown, JSON, and HTML formats.
"""

import json
import logging
from datetime import datetime
from pathlib import Path

from .models import (
    TraceReport, ClaimVerification, EvidenceStrength, SourceReliability,
)
from .config import Config

logger = logging.getLogger(__name__)


STRENGTH_ICONS = {
    EvidenceStrength.STRONG: "[STRONG]",
    EvidenceStrength.MODERATE: "[MODERATE]",
    EvidenceStrength.WEAK: "[WEAK]",
    EvidenceStrength.CONTRADICTORY: "[DISPUTED]",
    EvidenceStrength.NONE_FOUND: "[NO EVIDENCE]",
}

RELIABILITY_LABELS = {
    SourceReliability.HIGH: "High",
    SourceReliability.MEDIUM: "Medium",
    SourceReliability.LOW: "Low",
    SourceReliability.UNKNOWN: "Unknown",
}


def generate_markdown(report: TraceReport) -> str:
    """Generate a Markdown-formatted evidence trace report."""
    lines = []

    # Header
    lines.append(f"# Evidence Trace Report")
    lines.append(f"")
    lines.append(f"**Document:** {report.document_name}")
    lines.append(f"**Generated:** {report.generated_at}")
    lines.append(f"**Total Claims Found:** {report.total_claims}")
    lines.append(f"**Claims Verified:** {report.verified_count}/{report.total_claims}")
    lines.append(f"**Average Confidence:** {report.avg_confidence:.1%}")
    lines.append(f"")

    # Summary
    lines.append(f"---")
    lines.append(f"")
    lines.append(f"## Summary")
    lines.append(f"")

    # Count by verdict type
    strong = sum(1 for v in report.verifications if v.overall_strength == EvidenceStrength.STRONG)
    moderate = sum(1 for v in report.verifications if v.overall_strength == EvidenceStrength.MODERATE)
    weak = sum(1 for v in report.verifications if v.overall_strength == EvidenceStrength.WEAK)
    disputed = sum(1 for v in report.verifications if v.overall_strength == EvidenceStrength.CONTRADICTORY)
    unverified = sum(1 for v in report.verifications if v.overall_strength == EvidenceStrength.NONE_FOUND)

    lines.append(f"| Category | Count |")
    lines.append(f"|----------|-------|")
    lines.append(f"| Well-Supported | {strong} |")
    lines.append(f"| Partially Supported | {moderate} |")
    lines.append(f"| Weakly Supported | {weak} |")
    lines.append(f"| Disputed | {disputed} |")
    lines.append(f"| Unverified | {unverified} |")
    lines.append(f"")

    # Detailed results
    lines.append(f"---")
    lines.append(f"")
    lines.append(f"## Detailed Claim Analysis")
    lines.append(f"")

    for v in report.verifications:
        icon = STRENGTH_ICONS.get(v.overall_strength, "[?]")
        lines.append(f"### Claim #{v.claim.id}: {icon}")
        lines.append(f"")
        lines.append(f"> {v.claim.text}")
        lines.append(f"")
        lines.append(f"- **Type:** {v.claim.claim_type.value}")
        lines.append(f"- **Verdict:** {v.verdict}")
        lines.append(f"- **Confidence:** {v.overall_score:.1%}")
        lines.append(f"- **Sources Found:** {len(v.evidence_list)} "
                     f"({v.supporting_count} supporting, {v.contradicting_count} contradicting)")
        lines.append(f"")

        if v.evidence_list:
            lines.append(f"**Evidence:**")
            lines.append(f"")
            for i, e in enumerate(v.evidence_list, 1):
                stance = "Supports" if e.supports_claim else "Contradicts"
                rel = RELIABILITY_LABELS.get(e.source.reliability, "Unknown")
                lines.append(f"{i}. **[{stance}]** (confidence: {e.confidence_score:.1%}, source reliability: {rel})")
                lines.append(f"   - Source: [{e.source.title}]({e.source.url})")
                lines.append(f"   - *\"{e.relevant_text[:200]}\"*")
                lines.append(f"")
        else:
            lines.append(f"*No evidence found for this claim.*")
            lines.append(f"")

        lines.append(f"---")
        lines.append(f"")

    # Footer
    lines.append(f"*Report generated by Evidence Tracer Agent v0.1.0*")

    return '\n'.join(lines)


def generate_json(report: TraceReport) -> str:
    """Generate a JSON-formatted evidence trace report."""
    data = {
        "document_name": report.document_name,
        "generated_at": report.generated_at,
        "total_claims": report.total_claims,
        "verified_count": report.verified_count,
        "average_confidence": round(report.avg_confidence, 3),
        "summary": {
            "strong": sum(1 for v in report.verifications if v.overall_strength == EvidenceStrength.STRONG),
            "moderate": sum(1 for v in report.verifications if v.overall_strength == EvidenceStrength.MODERATE),
            "weak": sum(1 for v in report.verifications if v.overall_strength == EvidenceStrength.WEAK),
            "disputed": sum(1 for v in report.verifications if v.overall_strength == EvidenceStrength.CONTRADICTORY),
            "unverified": sum(1 for v in report.verifications if v.overall_strength == EvidenceStrength.NONE_FOUND),
        },
        "verifications": [],
    }

    for v in report.verifications:
        ver_data = {
            "claim_id": v.claim.id,
            "claim_text": v.claim.text,
            "claim_type": v.claim.claim_type.value,
            "verdict": v.verdict,
            "confidence": v.overall_score,
            "strength": v.overall_strength.value,
            "supporting_count": v.supporting_count,
            "contradicting_count": v.contradicting_count,
            "evidence": [],
        }
        for e in v.evidence_list:
            ver_data["evidence"].append({
                "supports_claim": e.supports_claim,
                "strength": e.strength.value,
                "confidence": e.confidence_score,
                "source": {
                    "url": e.source.url,
                    "title": e.source.title,
                    "domain": e.source.domain,
                    "reliability": e.source.reliability.value,
                    "snippet": e.source.snippet,
                },
            })
        data["verifications"].append(ver_data)

    return json.dumps(data, indent=2)


def generate_html(report: TraceReport) -> str:
    """Generate an HTML-formatted evidence trace report."""
    md_content = generate_markdown(report)

    # Convert simple markdown to HTML
    html_body = md_content
    # Headers
    html_body = html_body.replace("# Evidence Trace Report", "<h1>Evidence Trace Report</h1>")

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Evidence Trace Report - {report.document_name}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
               max-width: 900px; margin: 0 auto; padding: 2rem; color: #333; }}
        h1 {{ color: #1a1a2e; border-bottom: 3px solid #16213e; padding-bottom: 0.5rem; }}
        h2 {{ color: #16213e; margin-top: 2rem; }}
        h3 {{ color: #0f3460; }}
        blockquote {{ background: #f0f4f8; border-left: 4px solid #0f3460;
                     padding: 1rem; margin: 1rem 0; }}
        table {{ border-collapse: collapse; width: 100%; margin: 1rem 0; }}
        th, td {{ border: 1px solid #ddd; padding: 0.5rem 1rem; text-align: left; }}
        th {{ background: #16213e; color: white; }}
        .strong {{ color: #27ae60; font-weight: bold; }}
        .moderate {{ color: #f39c12; font-weight: bold; }}
        .weak {{ color: #e67e22; font-weight: bold; }}
        .disputed {{ color: #e74c3c; font-weight: bold; }}
        .none {{ color: #95a5a6; font-weight: bold; }}
        hr {{ border: none; border-top: 1px solid #ddd; margin: 2rem 0; }}
        a {{ color: #0f3460; }}
        .meta {{ color: #666; font-size: 0.9rem; }}
        .evidence-item {{ background: #fafafa; padding: 0.8rem; margin: 0.5rem 0;
                         border-radius: 4px; border: 1px solid #eee; }}
    </style>
</head>
<body>
    <h1>Evidence Trace Report</h1>
    <div class="meta">
        <p><strong>Document:</strong> {report.document_name}</p>
        <p><strong>Generated:</strong> {report.generated_at}</p>
        <p><strong>Claims:</strong> {report.verified_count}/{report.total_claims} verified
           | Average Confidence: {report.avg_confidence:.1%}</p>
    </div>
    <hr>
"""

    # Summary table
    strong = sum(1 for v in report.verifications if v.overall_strength == EvidenceStrength.STRONG)
    moderate = sum(1 for v in report.verifications if v.overall_strength == EvidenceStrength.MODERATE)
    weak = sum(1 for v in report.verifications if v.overall_strength == EvidenceStrength.WEAK)
    disputed = sum(1 for v in report.verifications if v.overall_strength == EvidenceStrength.CONTRADICTORY)
    unverified = sum(1 for v in report.verifications if v.overall_strength == EvidenceStrength.NONE_FOUND)

    html += f"""
    <h2>Summary</h2>
    <table>
        <tr><th>Category</th><th>Count</th></tr>
        <tr><td class="strong">Well-Supported</td><td>{strong}</td></tr>
        <tr><td class="moderate">Partially Supported</td><td>{moderate}</td></tr>
        <tr><td class="weak">Weakly Supported</td><td>{weak}</td></tr>
        <tr><td class="disputed">Disputed</td><td>{disputed}</td></tr>
        <tr><td class="none">Unverified</td><td>{unverified}</td></tr>
    </table>
    <hr>
    <h2>Detailed Claim Analysis</h2>
"""

    for v in report.verifications:
        strength_class = {
            EvidenceStrength.STRONG: "strong",
            EvidenceStrength.MODERATE: "moderate",
            EvidenceStrength.WEAK: "weak",
            EvidenceStrength.CONTRADICTORY: "disputed",
            EvidenceStrength.NONE_FOUND: "none",
        }.get(v.overall_strength, "none")

        html += f"""
    <h3>Claim #{v.claim.id} <span class="{strength_class}">[{v.overall_strength.value.upper()}]</span></h3>
    <blockquote>{v.claim.text}</blockquote>
    <p><strong>Type:</strong> {v.claim.claim_type.value} |
       <strong>Verdict:</strong> {v.verdict} |
       <strong>Confidence:</strong> {v.overall_score:.1%}</p>
    <p><strong>Sources:</strong> {len(v.evidence_list)} total
       ({v.supporting_count} supporting, {v.contradicting_count} contradicting)</p>
"""
        if v.evidence_list:
            for i, e in enumerate(v.evidence_list, 1):
                stance = "Supports" if e.supports_claim else "Contradicts"
                stance_color = "#27ae60" if e.supports_claim else "#e74c3c"
                rel = RELIABILITY_LABELS.get(e.source.reliability, "Unknown")
                html += f"""
    <div class="evidence-item">
        <strong style="color:{stance_color}">{i}. [{stance}]</strong>
        (confidence: {e.confidence_score:.1%}, reliability: {rel})<br>
        <a href="{e.source.url}" target="_blank">{e.source.title}</a><br>
        <em>"{e.relevant_text[:200]}"</em>
    </div>
"""
        else:
            html += "    <p><em>No evidence found for this claim.</em></p>\n"

        html += "    <hr>\n"

    html += """
    <p class="meta"><em>Report generated by Evidence Tracer Agent v0.1.0</em></p>
</body>
</html>"""

    return html


def save_report(report: TraceReport, fmt: str = "markdown", config: Config = None) -> Path:
    """
    Save a report to disk.

    Args:
        report: The TraceReport to save.
        fmt: Output format - 'markdown', 'json', or 'html'.
        config: Configuration (for output directory).

    Returns:
        Path to the saved report file.
    """
    if config is None:
        config = Config()

    config.ensure_output_dir()

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    doc_slug = report.document_name.replace(" ", "_").replace(".", "_")[:30]

    generators = {
        "markdown": (generate_markdown, ".md"),
        "json": (generate_json, ".json"),
        "html": (generate_html, ".html"),
    }

    generator, ext = generators.get(fmt, (generate_markdown, ".md"))
    content = generator(report)

    filename = f"evidence_report_{doc_slug}_{timestamp}{ext}"
    filepath = config.output_dir / filename

    filepath.write_text(content, encoding='utf-8')
    logger.info(f"Report saved to {filepath}")

    return filepath
